package: minimal_pkg

platform:
  - linux-64

engine:
   - python=2

before_script:
  - python -V

script:
  - conda build conda.recipe

build_targets:
    files: /opt/anaconda/conda-bld/*/minimal_pkg*.tar.bz2
    channels: '%(branch)s'
